### PR TITLE
Increase thumb touch area to start dragging gesture

### PR DESCRIPTION
**Pull request by jeroentrappers**
I had complaint from my users that the slider was difficult to use.

### CODE REVIEW

**Comment by boeledi** [comment]
Hi Jeroen,

Thanks for this proposal.  If I spotted well the changes (since there was a lot of reformatting), it is only related to the "_validateActiveThumb" method.

I agree with you however, I would rather prefer letting the application pass a parameter (e.g."touchRadiusExpansionRatio" (default: 1.0)) rather than a hardcoded a value (you mentioned a hardcoded value of 20.0, right)?  This parameter would then be used to define the new radix, based on the thumbShape preferred size.

The rationale is because if the _sliderTheme.thumbShape.getPreferredSize() is changed by the developer, your radix of 20.0 might not be relevant...

What do you think?

Regards, 

Didier

**Comment by jeroentrappers** [comment]
Hi Didier,
 
thank you for the feedback. I agree with the remarks and will update the PR accordingly. 

The 20.0 rather was a quick and dirty fix for my usage. It works well and is following the Apple Human interface guidelines that the touch surface of any interaction should be at least 40x40. \

Kind regards,

Jeroen

**Comment by jeroentrappers** [comment]
I've cleaned up the PR and implemented your feedback.

**Comment by boeledi** [comment]
Hi Jeroen,

Thanks again for your input.

Merged !!

Didier

**Comment by jeroentrappers** [comment]
Thanks! I'd be great if you push 0.0.5 it to the dart packages as well ;-)

**Comment by boeledi** [comment]
even better, it became version 1.0.0

Thanks a lot

**Pull request merged**
